artifact_location: file:///C:/Users/iamaj/PycharmProjects/mlflow_demo1/myfolder/0
creation_time: 1704883492282
experiment_id: '0'
last_update_time: 1704883492282
lifecycle_stage: active
name: Default
